import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'

import Layout from '../components/Layout'

import content from '../public/data.json'

const Crew: NextPage = () => {
  const [currentIndex, setCurrentIndex] = useState<number>(0)
  const crewData = content.crew[currentIndex]

  return (
    <div className="min-h-screen w-full bg-crew-mobile md:bg-crew-tablet xl:bg-crew-desktop bg-cover bg-no-repeat">
      <Head>
        <title>Meet your crew</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Layout>
        <section className="text-white pt-6 text-center">
          <h1 className="font-barlow-condensed text-subheading2 uppercase pb-8">
            <span className="text-white text-opacity-25 pr-2">02</span> Meet
            your crew
          </h1>

          <Image
            src={crewData.images.png}
            alt={crewData.name}
            width={crewData.images.width / 3}
            height={crewData.images.height / 3}
          />

          <section className="space-x-4 py-5 border-t-[1px] border-opacity-20 -mt-1">
            {content.crew.map((crewMember, index) => (
              <button
                className={`w-[10px] h-[10px] rounded-full bg-white ${
                  currentIndex === index ? 'bg-opacity-100' : 'bg-opacity-20'
                }`}
                key={crewMember.name}
                onClick={() => setCurrentIndex(index)}
              />
            ))}
          </section>

          <article>
            <h3 className="font-bellefair text-subheading2 text-white text-opacity-50 uppercase pb-2">
              {crewData.role}
            </h3>
            <h2 className="font-bellefair text-2xl uppercase pb-5">
              {crewData.name}
            </h2>
            <p className="font-barlow text-base text-space-accent">
              {crewData.bio}
            </p>
          </article>
        </section>
      </Layout>
    </div>
  )
}

export default Crew
