import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout'
import content from '../data.json'

const Home: NextPage = () => {
  return (
    <div className="min-h-screen w-full bg-home-mobile md:bg-home-tablet xl:bg-home-desktop bg-cover bg-no-repeat">
      <Head>
        <title>Lets go to space!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Layout>
        <section className="text-white pt-12 md:pt-28 text-center lg:text-left">
          <h2 className="font-barlow-condensed text-subheading2 md:text-xl lg:text-heading5 uppercase text-space-accent">
            So, you want to travel to
          </h2>
          <h1 className="font-bellefair text-[80px] md:text-heading1 md:pt-4 lg:pt-6 uppercase">
            Space
          </h1>
          <p className="font-barlow text-space-accent text-base lg:text-lg mx-auto lg:mx-0 md:leading-7 lg:leading-8 md:max-w-sm lg:max-w-md p-2 lg:p-0">
            Let’s face it; if you want to go to space, you might as well
            genuinely go to outer space and not hover kind of on the edge of it.
            Well sit back, and relax because we’ll give you a truly out of this
            world experience!
          </p>
        </section>
        <button className="block font-bellefair uppercase text-xl md:text-heading4 text-space-black leading-6 tracking-wide bg-white h-36 w-36 md:h-60 md:w-60 lg:h-72 lg:w-72 rounded-full mx-auto lg:mr-0 mt-20 md:mt-40">
          Explore
        </button>
      </Layout>
    </div>
  )
}

export default Home
